cuda_visible_devices: "0"
device: gpu

#dataset_name: BBC
logger_name: df_logger_cw_BBC.csv
model_name: Extended_Anneal_BBC
type_model: GAT #GCN
baseline: False #Always False for learned graphs
type_graph: full #full aka sliding window #min #max
normalized: False
unified_nodes: True #False
binarized: False
multi_layer: False

data_paths:
  path_logger: /scratch2/rldallitsako/HomoGraphs_BBC/ #/scratch/mbugueno/HomoGraphs_HND/
  results_folder: /home/rldallitsako/AttGraphs/GNN_Results_Classifier/Attention/BBC/ #/home/mbugueno/AttGraphs/GNN_Results_Classifier/Attention/
  root_graph_dataset: /scratch2/rldallitsako/datasets/AttnGraphs_BBC/ #/scratch/datasets/AttnGraphs_HND/

load_data_paths:
  in_path: "scratch2/rldallitsako/datasets/BBC/" #"/scratch/datasets/HyperNews/"
  data_train: ""
  labels_train: ""
  data_test: ""
  labels_test: ""
  with_val: True

model_arch_args:
  num_classes: 5
  lr: 0.001
  dropout: 0.2
  dim_features : [64, 128, 256]
  n_layers: [1, 2, 3]
  num_runs: 5

batch_size: 32
with_cw: True

trainer_args:
  max_epochs: 50
  enable_progress_bar: False

early_args:
  patience: 5
  min_delta: 0.001  
